version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    open-pull-requests-limit: 5

    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    labels:
      - "dependencies"
      - "automated"

    assignees:
      - tao-sense